/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 26-���-2015 20:37:58 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 ;

/* Drop Tables */

DROP TABLE IF EXISTS `CITIES` CASCADE
;

DROP TABLE IF EXISTS `COUNTRIES` CASCADE
;

DROP TABLE IF EXISTS `INVITES` CASCADE
;

DROP TABLE IF EXISTS `USERS` CASCADE
;

/* Create Tables */

CREATE TABLE `CITIES`
(
	`id_city` INT NOT NULL AUTO_INCREMENT,
	`id_country` INT NOT NULL,
	`city_name` NVARCHAR(50) NOT NULL,
	CONSTRAINT `PK_CITIES` PRIMARY KEY (`id_city`)
)

;

CREATE TABLE `COUNTRIES`
(
	`id_country` INT NOT NULL AUTO_INCREMENT,
	`country_name` NVARCHAR(50) NOT NULL,
	CONSTRAINT `PK_COUNTRIES` PRIMARY KEY (`id_country`)
)

;

CREATE TABLE `INVITES`
(
	`invite` INT NOT NULL AUTO_INCREMENT,
	`status` TINYINT NOT NULL DEFAULT 0,
	`date_status` TIMESTAMP(0) NOT NULL DEFAULT current_timestamp(),
	CONSTRAINT `PK_INVITES` PRIMARY KEY (`invite`)
)

;

CREATE TABLE `USERS`
(
	`id_user` INT NOT NULL AUTO_INCREMENT,
	`login` NVARCHAR(50) NOT NULL,
	`password` NVARCHAR(50) NOT NULL,
	`phone` NVARCHAR(50) NOT NULL,
	`id_city` INT NOT NULL,
	`invite` INT NOT NULL,
	CONSTRAINT `PK_USERS` PRIMARY KEY (`id_user`)
)

;

/* Create Foreign Key Constraints */

ALTER TABLE `CITIES` 
 ADD CONSTRAINT `FK_CITIES_COUNTRIES`
	FOREIGN KEY (`id_country`) REFERENCES `COUNTRIES` (`id_country`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `USERS` 
 ADD CONSTRAINT `FK_USERS_CITIES`
	FOREIGN KEY (`id_city`) REFERENCES `CITIES` (`id_city`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `USERS` 
 ADD CONSTRAINT `FK_USERS_INVITES`
	FOREIGN KEY (`invite`) REFERENCES `INVITES` (`invite`) ON DELETE Restrict ON UPDATE Restrict
;

SET FOREIGN_KEY_CHECKS=1 ;


INSERT INTO COUNTRIES (country_name)
VALUES ('Украина'),
('Беларусь'),
('Россия'),
('Германия'),
('Франция');

INSERT INTO CITIES (id_country, city_name)
VALUES (1, 'Киев'),
(2, 'Минск'),
(3, 'Москва'),
(4, 'Берлин'),
(5, 'Париж');

INSERT INTO INVITES (invite)
VALUES ('444789'),
('234678'),
('741852'),
('456321'),
('789654'),
('963258');

